### ISSUE TITLE
Error fetching weatherflow_forecast data: Update failed: Cannot connect to host

### ISSUE THREAD

**Issue by 10bias** [briis/weatherflow_forecast#107]
**Describe the bug**
I randomly get an error that the integration can not connect to swd.weatherflow.com. Here the error message from the log

`Error fetching weatherflow_forecast data: Update failed: Cannot connect to host swd.weatherflow.com:443 ssl:default [Try again]`

When i got this error the sensors have no status.

I have already checked the internet connection and i have build a monitor for swd.weatherflow.com:443. The internet connection and the monitor is stable.

I have also set the logging for the integration to debug. But in the log I only get this one error message

**To Reproduce**
I can not reproduce this. This occurs randomly several times a day.

**Comment by briis** [comment]
This is a hard one to debug. Personally I never see this, and I would normally say this is Internet related and not the integration.

Is the monitor you build and your Home Assistant on the same VLAN? (If you are using VLAN's)

**Comment by 10bias** [comment]
This was a problem with resolving dns and adguard. After fixing this weatherflow works again.
