### ISSUE TITLE
Integration is only providing a single entity and no additional sensors.

### ISSUE THREAD

**Issue by CommittotheIndian** [briis/weatherflow_forecast#12]
**Describe the bug**
Added the integration per the instructions but it only adds a single entity and no additional sensors. I do still have the Weatherflow (Core) integration installed but I wouldn't think that would matter since you changed domains.

**Expected behavior**
A full list of sensors available via my weather station as depicted in the instructions/Read Me as well as the past integration.

**Screenshots**
![image](https://github.com/briis/weatherflow_forecast/assets/60204668/d6c3f0fd-c2d5-4114-b442-9ec17388bf73)

**Additional context**
From the system logs:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:359
Integration: Sensor (documentation, issues)
First occurred: 12:57:21 PM (1 occurrences)
Last logged: 12:57:21 PM

Error while setting up weatherflow_forecast platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/weatherflow_forecast/sensor.py", line 399, in async_setup_entry
    entities: list[WeatherFlowSensor[Any]] = [
                                             ^
  File "/config/custom_components/weatherflow_forecast/sensor.py", line 401, in <listcomp>
    for description in SENSOR_TYPES if getattr(coordinator.data.sensor_data, description.key) is not None
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyweatherflow_forecast/data.py", line 807, in wind_cardinal
    return direction_array[int((self._wind_direction + 11.25) / 22.5)]
                                ~~~~~~~~~~~~~~~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

**Comment by briis** [comment]
What HW do you have? AIR & SKY or a Tempest device

**Comment by briis** [comment]
I will shortly be releasing V0.3.1 where I try to fix this if you are running the older HW. As I don't have that available, I cannot test it myself.

**Comment by CommittotheIndian** [comment]
> What HW do you have? AIR & SKY or a Tempest device

I am running Tempest.

**Comment by briis** [comment]
Could you try and install the latest version and let me know if that makes a difference

**Comment by baylanger** [comment]
Seems like I had the same issue since 0.3.0 and 0.3.1 shows sensor.

@briis merci for the quick fix!

**Comment by CommittotheIndian** [comment]
0.3.1 does not appear to have fixed it.

I tried updating and completing removing the integration (and HACS install then starting over.

When I first opened the integration after reinstalling, it showed multiple sensors for a split second a couple times. 

https://github.com/briis/weatherflow_forecast/assets/60204668/7b7fd326-9cb4-4f5e-9127-2a8a10c932dc

**Comment by baylanger** [comment]
@CommittotheIndian Have you tried to do the same using the web UI? Just to clear out any odd bug with the smart app.

**Comment by CommittotheIndian** [comment]
I did not at the last comment, I was away from the house. 

I have since tired via webUI and still the no additional sensors.

**Comment by briis** [comment]
Looking closely at your error log above, it seems that you are not getting a value for wind direction, and then the calculation of the wind cardinal fails as it tries to do math on a None value. I have just made a quick fix that will ensure it does not fail if the wind direction value is not found, so the sensors should load.
However it is strange that there is no value for wind direction - are you sure your Tempest is running as it should?

0.3.2 will be out soon, to implement this fix, and please let me know how that goes.

**Comment by CommittotheIndian** [comment]
So I think it's a conflict with the Core Weatherflow integration. 

While I am having some issues with my tempest (battery dying) it was working fine at the time of installation 

When I installed your component, all wind related sensors in the Core integration went unavailable. 

I have uninstalled both yours and the Core. I reinstalled yours and now I have all sensors. I reinstalled Core and do not have win related. 

If I reverse that and uninstall yours and reinstall Core, I get wind back.

**Comment by briis** [comment]
> So I think it's a conflict with the Core Weatherflow integration.

I don't think this is the case. I accept that this it was is happening at your site, but I have now tried on 3 different HA instances and I cannot provoke any errors by having both installed. I have Wind Sensors on both integration everywhere I install it.

I simply can't see one good reason why they should conflict. This could be the case if you installed the old integration, that has the same domain name, but with this integration you have different domain names and different unique id's for all sensors and on top of that they use two very different methods to retrieve data. 

Sp unless you can provide any logfiles that show some errors I have nothing to work with, and cannot help.

**Comment by briis** [comment]
And btw. all your issues with sensors can come from the fact that you have battery issues. If you look in your Tempest APP you can see the status of the Voltage, and if that gets too low, Wind Sensors will stop reporting. See more in this article: https://help.weatherflow.com/hc/en-us/articles/360048877194-Solar-Power-Rechargeable-Battery

**Comment by briis** [comment]
As there is no new information, I will assume it is fixed, and close the issue.
