### ISSUE TITLE
Unable to enter Station ID ST-00101xxx in configuration.

### ISSUE THREAD

**Issue by jaywking** [briis/weatherflow_forecast#130]
Hi

Trying to update to 1.0.9 and re-configuring (for some reason), I'm unable to enter my station Id (ST-00101xxx).  The entry for Station ID will not accept "ST-" and will not accept a "0" as the first character.

**Comment by briis** [comment]
This is not your Station ID. Please see the [Configuration Section](https://github.com/briis/weatherflow_forecast?tab=readme-ov-file#configuration) in the README file on how to obtain your Station ID.

**Comment by briis** [comment]
No feedback for several weeks. Assume solved.
