### ISSUE TITLE
Can't reconfigure integration

### ISSUE THREAD

**Issue by rmorlenSplunk** [briis/weatherflow_forecast#141]
**Describe the bug**
I have tried reconfiguring the integration.  I deleted the integration, restarted HA, then downloaded the integration, restarted HA. Can't get to the configuration page/settings. 

**Expected behavior**
After removing and reinstalling the integration I should be able to configure the integration.  Also, how would I add a second tempest?

**Additional context**
Whenever I click on the integration (where I would expect to see configuration), it goes to the following page:

![Screenshot 2024-07-16 at 8 57 48 AM](https://github.com/user-attachments/assets/7471e281-60f9-4f8e-9b25-c8c3a24c5499)

**Comment by briis** [comment]
After you have installed it from HACS, as it seems you have done from the screenshoot. And restarted Home Assistant, the correct procedure for installing is:
* Click on 'Settings' in the Sidebar
* Now click on 'Devices & services'
* In the lower right corner click on '+ ADD INTEGRATION'
* From here search for 'WeatherFlow'
* WeatherFlow will show up on the list
* Click on it, and you should see 3 different integrations, where two of the are the core integration of WeatherFlow and the third is this Custom Integration.
* If you select the third option (Which is marked with an open box symbol to show it is a Custom Integration) then the setup dialog should appear, and you enter the required values.

Are you saying, that if you follow the above procedure, it just jumps to the above Screenshot?

**Comment by briis** [comment]
> Also, how would I add a second tempest?

You just add the integration one more time and enter a different Station ID, belonging to the other Tempest device. That would create a second instance

**Comment by rmorlenSplunk** [comment]
Ok.  That is working now.  I have it working now.  I thought I had to configure in via HACS, not System integrations.  I misunderstood the instructions.

Thank you.  Sorry for being stupid.
Randy

From: Bjarne Riis ***@***.***>
Date: Wednesday, July 17, 2024 at 12:09 AM
To: briis/weatherflow_forecast ***@***.***>
Cc: Randy Morlen ***@***.***>, Author ***@***.***>
Subject: Re: [briis/weatherflow_forecast] Can't reconfigure integration (Issue #141)

After you have installed it from HACS, as it seems you have done from the screenshoot. And restarted Home Assistant, the correct procedure for installing is:

  *   Click on 'Settings' in the Sidebar
  *   Now click on 'Devices & services'
  *   In the lower right corner click on '+ ADD INTEGRATION'
  *   From here search for 'WeatherFlow'
  *   WeatherFlow will show up on the list
  *   Click on it, and you should see 3 different integrations, where two of the are the core integration of WeatherFlow and the third is this Custom Integration.
  *   If you select the third option (Which is marked with an open box symbol to show it is a Custom Integration) then the setup dialog should appear, and you enter the required values.

Are you saying, that if you follow the above procedure, it just jumps to the above Screenshot?
