### ISSUE TITLE
Change displayed station name

### ISSUE THREAD

**Issue by pmendiuk** [briis/weatherflow_forecast#158]
Is there a way that I could change the displayed station name?

**Comment by briis** [comment]
The name is taken from the name you defined in the WeatherFlow APP, so if you change the Station Name there it will also change the name in the Integration.
However, you will have to remove and re-add the integration before that happens.
This is currently the only way to do it.

If it is very important to you, I might implement a feature to overwrite it in Home Assistant, but you are currently the only one who asked for this, so it seems like a big effort as there is a workaround.

**Comment by briis** [comment]
As no one else has opted in for this, I will close the issue.
