### ISSUE TITLE
Missing many entities like temperature & uv, but have about 30

### ISSUE THREAD

**Issue by bendavis** [briis/weatherflow_forecast#161]
It looks like this integration should provide a large number of sensors (I checked the box) but I'm seeing lots from the front page that are missing. I'm wondering if this is a common problem? Specifically I don't see temperature or UV index, but I do see things like battery, beaufort, distance last lightning strike, etc.

**Comment by briis** [comment]
Hi,
It is hard to help without more info. Do you see anything in the Log files? Have you checked the WeatherFlow app, to see if the missing data is present there and the station is online?
If you get some data, then it seems you have a valid Station ID and Token, but the missing data is not supplied by the Weather Station.

I have found that occasionally that I needed to restart the Weather Station itself, especially if your Hub has a green light, then it might be a defective Tempest device or it simply needs a restart.

Please give me more info and I will do my best to help.

**Comment by briis** [comment]
No new information, so this issue will be closed.
