### ISSUE TITLE
Making old "SKY" and "AIR"  sensors  available

### ISSUE THREAD

**Issue by pflugj** [briis/weatherflow_forecast#168]
Hi.
1st of all, THANKS for your brilliant work! 

I do however have a request.
I switched from 
"WeatherFlow Weather for Home Assistant" 
to
"WeatherFlow Forecast and Sensor integration for Home Assistant"
 
Because I had a **faulty SKY** device (Battery failed) and the old devices/spares where no longer available, 
I had to switch to Tempest.

The WeatherFlow support was so nice and provide me with this:
https://community.weatherflow.com/t/easy-sky-spa-battery-expansion-unofficial/12571
... and I was able to modify the old SKY and made it work again - GREAT :-)

So now I do have a setup where, 
the old **SKY and AIR** sensors are still connected to the new Tempest HUB! 

As you obviously know, the old integration provided ALL available sensors as:
SK-serial, AR-serial and TP-serial

Unfortunately the new integration provides only the Tempest Sensors, meaning I lose 1/2 of my sensors :-(

Question is:
Is there a way to make ALL sensors again available??

Thanks again for your briiliant work!!
Jurgen

**Comment by briis** [comment]
Hi Jürgen,
Unfortunately I do not have access to Sky and AIR devices anymore, as mine also died on me a few years ago, and as with you, WeatherFlows service was great, they send me a new Tempest device. So this is the only HW I have to test on, and even if I could get access to your Account, and would require a major rewrite as I then have to cater for device types, which I don't do now.
I am not saying it could not be done, but before I make a decision on that, have you tried the Core WeatherFlow integration, which uses UDP and should support AIR and SKY devices. This integration is not as comprehensive as mine, but it should bring back most of your old sensors. You can run both installations at the same time.

Could you try that and let me know how that works out?

**Comment by pflugj** [comment]
Hi. - that was quick :-)
Just tried that and it seems to work :-)
I was not aware that one can run both integration at the same time - stupid me :-(

As you mentioned: The core integration does not provide all the sensors!
![image](https://github.com/user-attachments/assets/5d253a6d-58d1-4916-938c-fac93574cb24)
compared to your integration:
![image](https://github.com/user-attachments/assets/f48c013e-0828-4d7f-a8d2-a60589234fa7)

I am making use of the old sky sensor to get the "solar radiation", that hits my solar panels.
I therefore mounted the old SKY sensor at an 90 degree angle to the solar panels, 
to get a better idea, what the actual power, hitting the solar panels is.

The old "Air" sensor is used to provide additional outdoor temperature sensors and lightning count.
The lightning count of Tempest does not really work for me, 
as it picks up a lot of interference from surrounding "electrical fences"

Cheers and thanks again for your brilliant integration  and your help
Jurgen

**Comment by briis** [comment]
You are welcome Jurgen. Thank you.
