### ISSUE TITLE
Sensor Refresh Rate

### ISSUE THREAD

**Issue by jjsracic** [briis/weatherflow_forecast#22]
Could you please allow the sensor refresh rate to be changed?   If you use the HA integration for WeatherFlow, the sensors appear to update in real time.  Seems as though the sensors in this project update ever 5 to 10 minutes?

**Comment by briis** [comment]
To not overflod WeatherFlows servers with requests, the update interval is a random number between 1 and 5, if the sensors are active, and between 25-35 minutes when sensors are not active.

I will not change this.

Instead I recommend that you install the Built-In Weatherflow integration, which pulls the data directly from your HUB, and then you can install this integration, and disable the sensors. That way you get realtime sensor updates, and the Weather Forecast.
If you need some of the extra sensors that this integration provides, you can still enable this.
