### ISSUE TITLE
Cannot add Repo

### ISSUE THREAD

**Issue by rtdean93** [briis/weatherflow_forecast#24]
I am trying to add the Repo... but when I try, it provides the following error - "https://github.com/briis/weatherflow_forecast is not a valid add-on repository"

I am following the README doc 
Select Custom Repositories and in the bottom add https://github.com/briis/weatherflow_forecast to the Repository field and under Category select Integration.

To test - I have been able to add other repos... like https://github.com/alexbelgium/hassio-addons and https://github.com/adamoutler/Addons so I know I have connectivity.

**Comment by briis** [comment]
You are writing 'add-on repository'. Just to make sure, you try add this from the HACS menu, yes? And not from the 'Add-On Store'?

These are two first steps, as outlined in the README:
- **Open HACS, click integrations, and then in the upper right corner click on the three dots.**
- Select Custom Repositories and in the bottom add `https://github.com/briis/weatherflow_forecast` to the *Repository* field and under *Category* select *Integration*.

I have just tried on 3 different instances of Home Assistant, and it works every time.

**Comment by rtdean93** [comment]
Thank you.  Its working now.
