### ISSUE TITLE
Restoration of previous binary and descriptive sensors?

### ISSUE THREAD

**Issue by ngrusz1** [briis/weatherflow_forecast#25]
I was just wondering if there are any plans to restore the various binary sensors and descriptive sensors that were present in the previous integration. At the moment, it looks like the following sensors are not yet available:

- binary_sensor.weatherflow_is_lightning
- binary_sensor.weatherflow_is_raining
- binary_sensor.weatherflow_is_freezing
- sensor.weatherflow_beaufort_description
- sensor.weatherflow_uv_description
- sensor.weatherflow_battery_mode
- sensor.weatherflow_station_information

I suspect the functionality of most of these could be duplicated using some Helpers, but I was just wondering if there were any plans to add them back into the integration itself. Thanks!

**Comment by briis** [comment]
I can confirm that the Binary Sensors will come back. They are on my ToDo list
The descriptive sensors, I left out on purpose to see if anyone asks for them 😀 
I will seriously consider also adding them.

I will add two new issues, one for Binary Sensors and one for the Descriptive Sensors as these require different work to be done. I close this, and then please track the two new issues.
