### ISSUE TITLE
WeatherFlow Forecast installs and then fails to setup

### ISSUE THREAD

**Issue by mark-1941** [briis/weatherflow_forecast#39]
When I install WeatherFlow Forecast integration it seems to install correctly, accepts my Weatherflow Sensor ID and API and then says failed to setup. I have tried creating a new API, with the same result. Not sure what is going on. Attached screen grab shows the messages. 

I moved from the original integration, and did remove it and reboot before installing the new integration. 

![400728189_626761306339238_6084253773048762409_n](https://github.com/briis/weatherflow_forecast/assets/145957072/10283cd6-4927-4a8c-ad7c-61973ac8a7e0)

**Comment by briis** [comment]
You have to use the STATION ID and not the sensor ID.
To get your Station ID, [login with your account](https://tempestwx.com/settings/stations/), select the station on the list, and then click Status. Here you will find your Station ID.

Please try this and let me know how that goes.

**Comment by mark-1941** [comment]
Thanks, I figured it was user error but needed someone to point out my stupid mistake......
