### ISSUE TITLE
Air density SI units only

### ISSUE THREAD

**Issue by Phrede** [briis/weatherflow_forecast#40]
Despite having HA configured for imperial units, and other sensors displayed with imperial units, air density is not.
<img width="408" alt="summary" src="https://github.com/briis/weatherflow_forecast/assets/14333041/d6cc0e76-42b1-43b7-83e4-b538e8bfba4e">

**Comment by Phrede** [comment]
The Tempest unit is lb/ft^3.  Maybe it's best to match that and not mix SI and Imperial in the same unit as gm/ft^3??

**Comment by briis** [comment]
I saw that, and the Imperial units are now lb/ft^3. Already implemented
