### ISSUE TITLE
Precipitation intensity missing

### ISSUE THREAD

**Issue by bobbanks** [briis/weatherflow_forecast#41]
**Describe the bug**
Missing "precipitation_intensity" sensor 

**Expected behavior**
Expected to find "precipitation_intensity" but it appears missing.  Other qualitative sensors ("beaufort_description", "pressure_trend") are present.

**Comment by briis** [comment]
Was left out on purpose. Wanted to see if anyone missed it - it appears you do 😀
It is on the ToDo list
