### ISSUE TITLE
Not able to add repository

### ISSUE THREAD

**Issue by knoxvol23** [briis/weatherflow_forecast#45]
**Describe the bug**
Not able to add repository.

Error is:  No RepositoryFile.MAINIFEST_JSON file found 'custom_components/weatherflow_forecast/RepositoryFile.MAINIFEST_JSON'

**To Reproduce**
1. Go to Integrations
2. Click on three dots
3. Scroll down to Custom Repositories
4. Enter https://github.com/briis/weatherflow_forecast
5. Enter Intergrations as the category
6. Click on Add
7. Error is produced within the entry window

**Expected behavior**
I expect for repository to be added

**Screenshots**
<img width="916" alt="Screenshot 2023-12-07 at 3 44 16 PM" src="https://github.com/briis/weatherflow_forecast/assets/153233736/1ae1757a-f939-491a-9eae-61060ea9e4c3">

Core 2023.12.0
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231206.0

**Comment by briis** [comment]
That is strange. I just tried to do it, and it worked right away, with the same version as your setup.
It is true that the file mentioned `RepositoryFile.MANIFEST_JSON` does not exist, but this is not described anywhere in the HACS documentation, you just need the `manifest.json` which is also present.

I think there is something messing around in your HACS installation, that might need cleaning up. Are you running the latest version of HACS (V1.33)?

**Comment by briis** [comment]
Thanks. I will close this now. Once your HACS issue is resolved, and it still not works, then please re-open.
