### ISSUE TITLE
Absolute Humidity off

### ISSUE THREAD

**Issue by TheRealWaldo** [briis/weatherflow_forecast#6]
The absolute humidity is being returned as 690Kg/m3, which just isn't physically possible :)

I think we might have the wrong unit of measurement there.

**Comment by briis** [comment]
Agree 😳 I'll look into it.

**Comment by briis** [comment]
Fixed in release 0.2.2 I had a multiply '*' instead of a plus '+' in the formula - that makes a BIG difference

**Comment by TheRealWaldo** [comment]
Thanks @briis !
