### ISSUE TITLE
Integration Hangs when selecting "add sensors from station"

### ISSUE THREAD

**Issue by Aham330** [briis/weatherflow_forecast#62]
Core 2024.1.2
superv 2023.12.0

Installed through HACS " WeatherFlow Forecast and Sensor integration for Home Assistant"

then went to devices services installed "weatherflow forecast" as explained. 

Added station ID and API. Solar so good. 

When selecting "Add sensors from the Weather Station" 

the integration Hangs.

**Comment by briis** [comment]
It is hard to help you without log files. Please look in the log and let me know what that says.

Also, you did restart HA after the HACS installation?

**Comment by Aham330** [comment]
I'm Sorry to say that I might have jumped the gun a bit. 
Apparently my Tempest itself is not providing any info because of its battery drain. While it looked as if I wasn't getting any data I think that is the reason for not being able to work. 
HACS has been installed for years so that's not the issue. 
I'm using weatherflow2mqtt but switched that off while using the core integration. 
Let me see first if I can get my Tempest charged and then try again.
For me its ok to either leave this open or close it and I could start a new issue incase.

Sorry again for jumping the gun.😇

**Comment by briis** [comment]
If the station has not been providing data for some time the JSON that is returned contains a lot of empty data and that is the reason it fails. I live in the North also and had to buy the Power Bank to ensure my Station had power in the Winter.

I will close it for now, and then please reopen or crate a new issue if it still fails.
