### ISSUE TITLE
All Sensors Unavailable 

### ISSUE THREAD

**Issue by mikecoscia** [briis/weatherflow_forecast#63]
Integration was working great. However, this morning I noticed all my sensors are unavailable and it states that they are no longer being provided.  All I have is the binary sensors.  Tried removing and reinstalling the integration, but no luck.  Tempest shows it is online.

**Comment by briis** [comment]
Please check that your device is still providing data. It might be offline for some reason.

**Comment by mikecoscia** [comment]
It was going on and off due to the weather.  Wasn't getting enough sun to top its batteries off.  I bought the kit to wire it for power, but haven't had a chance to install it yet.  As of right now, the app and website say it is online.  Although it does say it is in power save mode.  I'll give it some time to charge up and see what happens. Thanks for getting back to me!

**Comment by briis** [comment]
Once your station is operational again, and if it still not works then please create a new issue with the logs from Home Assistant
