### ISSUE TITLE
Local data?

### ISSUE THREAD

**Issue by timothybuchanan** [briis/weatherflow_forecast#68]
Are the sensors pulling data directly from the station, as the previous Weatherflow integration does? Or do they come from the cloud as the forecast does?

**Comment by briis** [comment]
This integration uses the REST API and as such ALL data is coming from the Cloud. If you want to have the sensors local, then you can install this Integration and only select the Forecast, and then the Core Integration called Weatherflow, which then pulls the sensors using UDP. Please note the core integration has fewer sensors available, but they are all local.

**Comment by timothybuchanan** [comment]
Thank you. Id love to see an integration that integrated (so to speak) the two approaches. Timothy Buchanan From: Bjarne RiisSent: Monday, January 15, 2024 23:01To: briis/weatherflow_forecastCc: timothybuchanan; AuthorSubject: Re: [briis/weatherflow_forecast] Local data? (Issue #68) This integration uses the REST API and as such ALL data is coming from the Cloud. If you want to have the sensors local, then you can install this Integration and only select the Forecast, and then the Core Integration called Weatherflow, which then pulls the sensors using UDP. Please note the core integration has fewer sensors available, but they are all local.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by briis** [comment]
We had a discussion on that, but mixing two API's in to one integration is not really a good idea. So The approach I suggest is currently the best solution

**Comment by timothybuchanan** [comment]
I understand. Thanks. Timothy Buchanan From: Bjarne RiisSent: Saturday, January 20, 2024 0:20To: briis/weatherflow_forecastCc: timothybuchanan; AuthorSubject: Re: [briis/weatherflow_forecast] Local data? (Issue #68) We had a discussion on that, but mixing two API's in to one integration is not really a good idea. So The approach I suggest is currently the best solution—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
