### ISSUE TITLE
Error while setting up weatherflow_forecast platform for sensor

### ISSUE THREAD

**Issue by davecpearce** [briis/weatherflow_forecast#69]
Hi there, unfortunately my weather station is in powersave mode due to limited amount of sun at the moment.  I might have to look into powering this during the winter.  I do not get wind data in the Weatherflow app but I can see current Brightness data.  All of my sensors are unavailable and sensor.weatherflow_sensors_illuminance is the one I am more interested in for automations I have. 

Would it be possible for the integration to load data that is available (sensor.weatherflow_sensors_illuminance) while I understand the other sensors would be unavailable as opposed to all data being unavailable? 

2024-01-16 13:10:43.021 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up weatherflow_forecast platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/weatherflow_forecast/sensor.py", line 442, in async_setup_entry
entities: list[WeatherFlowSensor[Any]] = [
^
File "/config/custom_components/weatherflow_forecast/sensor.py", line 444, in <listcomp>
for description in SENSOR_TYPES if getattr(coordinator.data.sensor_data, description.key) is not None
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyweatherflow_forecast/data.py", line 882, in uv_description
if self._wind_avg > float(key):
^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by briis** [comment]
Good idea. I'll try and see what I can do to make it work even with very little data.

**Comment by briis** [comment]
I looked in to the code and the error you are getting is actually a bug in underlying module:

> File "/usr/local/lib/python3.11/site-packages/pyweatherflow_forecast/data.py", line 882, in uv_description
if self._wind_avg > float(key):

I have fixed this error, and will put out a new version soon.

But to try and avoid the system from not loading when Power is low on the device, it would be nice to have some data to work with. I could remove my Power Booster, but then it will take some days before my system is down, so if your station is still low on power and I could get your station id, I could pull the raw data and use that as test. You can send it to me on my private email bjarne@briis.com

**Comment by davecpearce** [comment]
Thank you for looking into this @briis. I have emailed my station ID to you.

**Comment by briis** [comment]
Closed with release 1.0.6. Your station is still online, but your Tempest device is in Power Save Mode 3, meaning it does not report Wind as an example. So if you add the station now, you will get some sensors but not all of them. Once you are back to power, you can refresh the Integration and all the remaining sensors will be setup.
