### ISSUE TITLE
Hourly Forecast exceeds maximum size of 16384 bytes

### ISSUE THREAD

**Issue by markus99** [briis/weatherflow_forecast#74]
**Describe the bug**
State attributes for sensor.watchman_missing_entities exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

**To Reproduce**
Setup Hourly Forecast

**Expected behavior**
No error ;)

**Screenshots**
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:582
Integration: Recorder (documentation, issues)
First occurred: 12:45:16 PM (7 occurrences)
Last logged: 12:54:10 PM

State attributes for sensor.weatherflow_forecast_hourly exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for sensor.watchman_missing_entities exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

**Additional context**
Would love the ability to configure # of hours to request for the hourly forecast.  Appears integration currently is returning 227 hours into the future, whereas, at least for me, I am only utilizing the next 12.

Ie.  It's currently Friday at 1pm Central, and the hourly forecast goes through NEXT Sunday @ 11pm (over 9 days from now) - which, to be honest, and apologies to weather persons and AI algorithms, isn't likely to be close to accurate anyhow :P

![image](https://github.com/briis/weatherflow_forecast/assets/2835274/a8c43cd3-c199-45fc-9e1a-357faceb565b)

**Comment by briis** [comment]
Closing this. Is fixed with the 1.0.8 release.
