### ISSUE TITLE
Not a bug, I just need some help

### ISSUE THREAD

**Issue by ripvega** [briis/weatherflow_forecast#77]
I'm trying to add this to HA and am generating the API token.

It's asking me for "Authorization Callback URL (one per line)"

What should I be entering here?

**Comment by briis** [comment]
I am not really sure how to help with this. I suggest that you can in touch with WeatherFlow directly. Their support is always extremely helpful. Either use [this form](https://help.weatherflow.com/hc/en-us/requests/new) or write to support@weatherflow.com

**Comment by ripvega** [comment]
What did you use when testing to get the API?

**Comment by ripvega** [comment]
This is what is being asked for to get the API

<img width="901" alt="image" src="https://github.com/briis/weatherflow_forecast/assets/42817627/ddc936a3-0655-4818-98b3-ff258f1b1c30">

**Comment by ripvega** [comment]
I've figured it out.

What's actually needed is a personal use token rather than an API key.

Obtainable from settings/data authorisations, once logged in to your station.

**Comment by briis** [comment]
Exactly, I was just about to write that to you 👏

**Comment by ripvega** [comment]
No problem.

Could you add that info to the installation instructions?

**Comment by briis** [comment]
I updated the README file, to be more specific of what type of authorization one should choose.
