### ISSUE TITLE
Weather Entity Missing

### ISSUE THREAD

**Issue by deadrubberboy** [briis/weatherflow_forecast#92]
Hello,

I am missing the Weather entity so I can't utilize Weather Cards etc. I have redownloaded. All my real time sensor info works. Just don't have that. 

**To Reproduce**
Installed via HACS. All working but missing weather. entity

**Expected behavior**
readme says weather entity is included.

**Comment by briis** [comment]
Can post any logs from Home Assistant? I have not really anything to work with in your text.
the weather entity is always default, so unless it fails to setup, it should be there. And if it fails during setup, you should have data in the log files.

**Comment by deadrubberboy** [comment]
Uninstalled.  Reinstalled and that fixed it.  Thank you!
